finished 2b

diff --git a/makefile_mine b/makefile_mine
--- a/makefile_mine
+++ b/makefile_mine
@@ -1,19 +1,33 @@
-NUM?=1
-numbers=10 11 12 13 14 15 16 17 18 19 20 61 62
-tests=project$(NUM)-exampleIO
+#makefile for lab 2a pass off cases
+NUM:=2
+buckets:=80 100
+numbers_80:=0 1 2 3 4 5 6 7
+numbers_100:=0 
+tests:=Project$(NUM)bPassOffCases
+project:=Datalog Parser
 
-mine:
-	g++ *.cpp -o lab1
+.SILENT: all $(buckets)
 
-theirs: compile run
+all: $(buckets)
+	@rm $(tests)/out.txt
 
-run:
-	for number in $(numbers); \
+$(buckets):
+	echo "Bucket $@"; \
+	for number in ${numbers_$@} ; \
 	do \
-		./lab$(NUM) $(tests)/in$$number.txt > $(tests)/out.txt ; \
-		diff $(tests)/out$$number.txt $(tests)/out.txt || (echo "diff failed on test $$number \n") ; \
-	done
-	rm $(tests)/out.txt
+		echo "Running input $$number" ; \
+		./project$(NUM) $(tests)/$(NUM)-$@/input$$number.txt > $(tests)/out.txt ; \
+		diff -w $(tests)/$(NUM)-$@/answer$$number.txt $(tests)/out.txt || (echo "diff failed on test $$number \n") ; \
+	done \
 
 compile:
-	g++ -Wall -Werror -std=c++17 -g *.cpp -o lab$(NUM)
+	g++  -Werror -std=c++17 -g *.cpp -o project$(NUM)
+
+theirs: compile
+	make
+
+quick:
+	g++ *.cpp -o project$(NUM)
+
+mine: quick
+	make
